#!/bin/bash
set -euo pipefail

for dir in "$@"; do
  [[ -f "$dir/Dockerfile" ]] || continue
  name="$(basename "$dir")"
  for arg in "$dir/"*.arg; do
    arg_base="$(basename "$arg")"
    arg_name=${arg_base%.arg}
    for a in $(cat "$arg"); do
      jq -n \
        --arg dir "$dir" \
        --arg name "${name//_/-}" \
        --arg arg_name "$arg_name" \
        --arg a "$a" \
        --arg build_args "$arg_name=$a" \
        '{
          "dir": $dir,
          "name": ($name + "-" + $arg_name + $a),
          "build_args": ($arg_name + "=" + $a)
        }'
    done
  done
done | jq -c -r -s '.'
