on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python3 -m pip install --upgrade build twine
      - name: build package
        run: |
          export VERSION=0.0.0
          [[ "$GITHUB_REF" == "refs/tags/"* ]] && VERSION="${GITHUB_REF/refs\/tags\/v/}"
          python3 -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TWINE_PASSWORD }}
        if: startsWith(github.ref, 'refs/tags/')
