name: Reusable arena unit tests

on:
  workflow_call:
    inputs:
      arena_branch:
        required: true
        type: string

jobs:
  reusable_arena_unit_tests:
    name: Reusable arena unit tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Pre-install pinned packages for deprecations
        run: |
          python3 -m pip install wheel==0.38.4 setuptools==66.0.0
          pip list

      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: "${{ inputs.arena_branch }}"

      - name: Install tests dependencies
        run: |
          python3 -m pip install .["tests"]
          pip list

      - name: Run tests
        run: |
          pytest tests/test_gym_settings.py
          pytest tests/test_wrappers_settings.py
          pytest tests/test_recording_settings.py
          pytest tests/test_random.py
          pytest tests/test_speed.py
