on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Need to limit to specific python version because of 3.12 fails with `pip install .["tests"]`
      - run: python3 -m pip install wheel
      - run: python3 -m pip install .["tests"]
      - run: pytest tests/test_gym_settings.py
      - run: pytest tests/test_wrappers_settings.py
      - run: pytest tests/test_recording_settings.py
      - run: pytest tests/test_examples.py
      - run: pytest -k "test_speed_gym_mock or test_speed_wrappers_mock" tests/test_speed.py # Run only mocked tests
      - run: pytest -k "test_random_gym_mock or test_random_wrappers_mock" tests/test_random.py # Run only mocked tests
