on:
  pull_request: {}

jobs:
  test:
    uses: diambra/agents/.github/workflows/reusable_unit_tests.yaml@main
    with:
      arena_requirement_specifier: 'git+https://github.com/diambra/arena.git@${{ github.ref }}#egg='
      agents_ref: 'main'
