on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python3 -m pip install .["tests"]
      - run: pytest tests/test_gym_settings.py
      - run: pytest tests/test_wrappers_settings.py
      - run: pytest tests/test_recording_settings.py
      - run: pytest tests/test_random.py
      - run: pytest tests/test_speed.py
